import gzip
import shutil
from pathlib import Path
import numpy as np
import pandas
import rioxarray as rxr
import xarray as xr
import os
import joblib

# --------------------------------------------- ---------------------------------
# --------------------------------------------- ---------------------------------
def S3M_read_output_file(sPathMap,sPathMap_nc, sFileNameMap, sVarName):

    #Read 'sVarName' field from gzipped NetCDF file generated by S3M.
  

    path_gz = Path(sPathMap) / sFileNameMap
    # remove .gz from filename
    sFileNameMap_nc = sFileNameMap[:-3]
    path_nc = Path(sPathMap_nc) / sFileNameMap_nc

    # --- 1. Decompress the .gz file ---
    with gzip.open(path_gz, 'rb') as f_in:
        with open(path_nc, 'wb') as f_out:
            shutil.copyfileobj(f_in, f_out)

    # --- 2. Read the variables from NetCDF ---
    # ensure sVarName is a list
    if isinstance(sVarName, str):
        sVarName = [sVarName]

    a2dMaps = {}
    ds = xr.open_dataset(path_nc, decode_times=False)

    for var in sVarName:
        if var not in ds:
            raise KeyError(f"Variable '{var}' not found in {path_nc}")
        arr = np.flipud(ds[var].values)
        a2dMaps[var] = arr  # store each 2D map

    ds.close()
    path_nc.unlink(missing_ok=True)

    return a2dMaps

# --------------------------------------------- ---------------------------------
# --------------------------------------------- ---------------------------------
dem = "/home/idrologia/PhD_GiuliaBlandini/S3M_2D/inputs/dem/DEM_VDA.tif"
dem_da = rxr.open_rasterio(dem, engine='rasterio').sel(band=1).drop_vars('band').chunk({"x": 100, "y": 100})
lon_dem = dem_da.x.values
lat_dem = dem_da.y.values
dem_da = dem_da.where(dem_da != -9999)
# -------------------------------------------------------------------------------------
station_list = pandas.read_csv('/home/idrologia/share/PhD_GiuliaBlandini_dati/DATI/STATION_ID_VDA.csv')
# Replace commas with periods in the 'lat' and 'lon' columns
station_list['lat'] = station_list['lat'].str.replace(',', '.').astype(float)
station_list['lon'] = station_list['lon'].str.replace(',', '.').astype(float)
lat =[]
lon = []
for index, row in station_list.iterrows():
    lat_station = row['lat']
    lon_station = row['lon']
    # round at 6 number after comma
    lat_station = round(lat_station, 6)
    lon_station = round(lon_station, 6)
    lat.append(lat_station)
    lon.append(lon_station)

# -------------------------------------------------------------------------------------
path_output_runs = "/home/idrologia/share/PhD_GiuliaBlandini_dati/VDA_S3M_MeteoData/Output/"
path_pkl= "/home/idrologia/share/PhD_GiuliaBlandini_dati/DATI/input_meteo/"
path_extract = "/home/idrologia/share/PhD_GiuliaBlandini_dati/DATI/input_meteo/"
# -------------------------------------------------------------------------------------
list_var = ['AirTemperature', 'Rain', 'RelHumidity', 'IncRadiation']
start_date = '20071001'
end_date = '20240930'
period = pandas.date_range(start='20071001', end= '20240930 23:00', freq='H')
# -------------------------------------------------------------------------------------
list_runs_to_process = ['run_001']
n_stations = len(station_list)
# -------------------------------------------------------------------------------------
# Now loop on all runs and extract S3M output at station locations
for i_run, run in enumerate(list_runs_to_process):

    print(f'Processing run {i_run + 1} of {len(list_runs_to_process)}: {run}')

    # Preallocate (time, station, variable)
    ds_this_run = np.full((len(period), n_stations, len(list_var)), np.nan, dtype=np.float32)


    for date in period:
        path_to_file = os.path.join(path_output_runs, date.strftime('%Y/%m/%d'))
        file = f"MeteoData_{date.strftime('%Y%m%d%H')}00.nc.gz"
        full_path = os.path.join(path_to_file, file)

        if not os.path.exists(full_path):
            print(f"Missing file: {full_path}")
            continue

        ds = S3M_read_output_file(path_to_file,path_extract, file, list_var)
        mask = np.isnan(dem_da)

        for var in list_var:
            ds[var][mask] = np.nan

        ds_da = xr.DataArray(np.stack([ds[var] for var in list_var], axis=-1),dims=["lat", "lon", "variable"],coords={
                "lat": lat_dem,
                "lon": lon_dem,
                "variable": list_var,  # these are your variable names
            }, name=var)
        lon_query = xr.DataArray(lon, dims="points")
        lat_query = xr.DataArray(lat, dims="points")
        ds_meteo = ds_da.sel( lon=lon_query, lat=lat_query, method="nearest" )

        date_index = period.get_loc(date)
        # add the lat and lon dimensions
        ds_this_run[date_index , :, :] = ds_meteo.values
        print(f'Processed date {date.strftime("%Y-%m-%d %H:%M")}')

# Create xarray Dataset for the full run
lat_stations = station_list['lat'].tolist()
lon_stations = station_list['lon'].tolist()

ds_final = xr.Dataset(
    {var: (("time", "station"), ds_this_run[:, :, i]) for i, var in enumerate(list_var)},
    coords={
        "time": period,
        "station": np.arange(n_stations),
        "lat": ("station", np.array(lat_stations)),
        "lon": ("station", np.array(lon_stations)),
    }
)

# Save as NetCDF
output_file_nc = os.path.join(path_pkl, f"S3M_MeteoData_{start_date}_{end_date}.nc")
ds_final.to_netcdf(output_file_nc)
print(f"Saved {output_file_nc}")




#